(deftheme leuven-edit
  "Tiny edit of the leuven theme")

(custom-theme-set-variables
 'leuven-edit
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["black" "red3" "ForestGreen" "yellow3" "blue" "magenta3" "DeepSkyBlue" "gray50"]))

(custom-theme-set-faces
 'leuven-edit
 '(bold ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(bold-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "black"))))
 '(italic ((((class color) (min-colors 89)) (:slant italic :foreground "#1A1A1A"))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#0FB300"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#9B9B9B" :background "#EDEDED"))))
 '(highlight ((((class color) (min-colors 89)) (:underline nil :background "#FFF876"))))
 '(region ((((class color) (min-colors 89)) (:background "#ABDFFA"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:weight bold :background "#FBE448"))))
 '(isearch ((((class color) (min-colors 89)) (:weight bold :underline "#FF9632" :foreground nil :background "#FDBD33"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FF9999"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:underline "#FF9632" :background "#FFFF00"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#FFFF57"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#1A2F54") :foreground "#85CEEB" :background "#335EA8"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#4E4E4C") :foreground "#F0F0EF" :background "#9B9C97"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "yellow"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "gold"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#008ED1"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(success ((((class color) (min-colors 89)) (:foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#006FE0"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#8D8D84"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#8D8D84"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#036A07"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#006699"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#0000FF"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:weight normal :foreground "#6434A3"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#BA36A5"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#E5786D"))))
 '(button ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(header-line ((((class color) (min-colors 89)) (:weight bold :underline "black" :overline "black" :foreground "black" :background "#FFFF88"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(comint-highlight-input ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "lightgrey"))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "grey90"))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:box (:line-width 2 :style pressed-button) :foreground "black" :background "light grey"))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:underline t))))
 '(custom-changed ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-comment ((((class color) (min-colors 89)) (:background "gray85"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(custom-documentation ((((class color) (min-colors 89)) (nil))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:height 1.2 :weight bold :foreground "blue1"))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "red1"))))
 '(custom-invalid ((((class color) (min-colors 89)) (:foreground "yellow" :background "red"))))
 '(custom-link ((((class color) (min-colors 89)) (:underline t :foreground "blue1"))))
 '(custom-modified ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-rogue ((((class color) (min-colors 89)) (:foreground "pink" :background "black"))))
 '(custom-saved ((((class color) (min-colors 89)) (:underline t))))
 '(custom-set ((((class color) (min-colors 89)) (:foreground "blue" :background "white"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(custom-themed ((((class color) (min-colors 89)) (:foreground "white" :background "blue1"))))
 '(custom-variable-button ((((class color) (min-colors 89)) (:weight bold :underline t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "blue1"))))
 '(custom-visibility ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(file-name-shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(info-header-node ((((class color) (min-colors 89)) (:underline t :foreground "orange"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:underline t :foreground "dodger blue"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "black"))))
 '(info-node ((((class color) (min-colors 89)) (:underline t :foreground "blue"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(info-xref ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(match ((((class color) (min-colors 89)) (:weight bold :background "#FBE448"))))
 '(next-error ((((class color) (min-colors 89)) (:underline nil :background "#FFF876"))))
 '(nobreak-space ((((class color) (min-colors 89)) (:background "#CCE8F6"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#99CCFF"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:underline "red" :foreground nil :background "#FFDCDC"))))
 '(tool-bar ((((class color) (min-colors 89)) (:box (:line-width 1 :style released-button) :foreground "black" :background "gray75"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "black" :background "light yellow"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#F6EBFE"))))
 '(widget-button ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "dim gray"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(default ((t (:background "#EEEEEC" :foreground "#333333")))))

(provide-theme 'leuven-edit)
